### ISSUE TITLE
Some issues on deployment

### ISSUE THREAD

**Issue by uniibu** [danneu/koa-skeleton#14]
The Heroku deployment is not working since you made commit on Removing Babel.

You forgot to remove babel on `app.json` , the line:
`"postdeploy": "NODE_ENV=development node ./babel.reset_db"`
should be:
`"postdeploy": "NODE_ENV=development node ./sql/reset_db"`

It is also important to note that when deploying, `reset_db.js` requires `'../src/config'` which will load the default values since it does not initialised the `'dotenv'` module. So anything on the .env file will be ignored, so in case the user used a different db name other than `postgres://localhost:5432/koa-skeleton` then deployment will fail unless they manually change the default values on the `config.js`. 

Also the `// Sanity check: Ensure this isn't being run in production` on `reset_db.js` is useless since it will always be on `development` environment, unless it was run with a specific environment such as `NODE_ENV=production node ./sql/reset_db`.

I'd recommend requiring `dotenv` on the `reset_db.js` so that it will load the environment variables from the `.env` instead of the defaults.

**Comment by danneu** [comment]
Agreed. Thanks, haven't touched this project in a long time.
