### ISSUE TITLE
Improve doc/setup

### ISSUE THREAD

**Issue by jscari** [danneu/koa-skeleton#8]
Hi,

Thanks for the boilerplate.

Two things are missing in the README, it is kind of obvious when you know it but the app returns an error 500 without them :

1)  Add to the .env file (the template do not render without those two variables)

```
RECAPTCHA_SITEKEY=''
RECAPTCHA_SITESECRET=''
```

2) Init the db

```
npm run reset-db
```

**Comment by danneu** [comment]
Thanks, I definitely need to add these to the README.

I should also improve the project so that the Recaptcha is gracefully turned off if those env vars are missing.

**Comment by danneu** [comment]
Made some progress on the README: https://github.com/danneu/koa-skeleton/commit/94e56387d0970d752c706d29ad4165af4226ee50

Another thing I'd like to fix is that the current npm tasks fail if you have no `.env`: https://github.com/danneu/koa-skeleton/blob/94e56387d0970d752c706d29ad4165af4226ee50/package.json#L8-L9

I've never use it, but I think I should use something like https://www.npmjs.com/package/config to setup environment vars, especially in development.

**Comment by jscari** [comment]
Actually, I am on Windows and `npn start-dev` doesn't work.

The fix was easy, just add in index.js
`require('dotenv').config();`

https://www.npmjs.com/package/dotenv

**Comment by danneu** [comment]
Just pushed some code improvements that handle missing `RECAPTCHA_SITEKEY`.

Thanks, I'll look at the dotenv package right now. My `.env` stuff is a hack that I'm eager to replace.

**Comment by danneu** [comment]
That was simple: https://github.com/danneu/koa-skeleton/commit/550f5a8b3475929b6efc49d69884758277a2a972

**Comment by danneu** [comment]
Should be all resolved now
